create table if not exists users (
    user_id bigint generated by default as identity primary key,
    email varchar(254) not null,
    password_hash varchar(255),
    name varchar(50) not null,
    role varchar(20) not null default 'USER',
    status varchar(20) not null default 'ACTIVE',
    token_version integer not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    withdrawn_at timestamptz,
    manual_suspension boolean not null default false,
    manual_suspension_reason varchar(500),
    constraint uk_users_email unique (email),
    constraint ck_users_role check (role in ('USER', 'SELLER', 'ADMIN')),
    constraint ck_users_status check (status in ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
    constraint ck_users_token_version check (token_version >= 0)
);

create table if not exists seller_profiles (
    seller_id bigint generated by default as identity primary key,
    user_id bigint not null,
    business_name varchar(100) not null,
    business_number varchar(20) not null,
    latitude decimal(10, 7),
    longitude decimal(10, 7),
    delivery_radius_km decimal(8, 2),
    verification_status varchar(20) not null default 'PENDING',
    rejection_reason varchar(500),
    applied_at timestamptz not null,
    reviewed_at timestamptz,
    reviewed_by bigint,
    version bigint not null default 0,
    constraint fk_seller_profiles_user
        foreign key (user_id) references users (user_id) on delete cascade,
    constraint fk_seller_profiles_reviewer
        foreign key (reviewed_by) references users (user_id) on delete set null,
    constraint uk_seller_profiles_user unique (user_id),
    constraint uk_seller_profiles_business_number unique (business_number),
    constraint ck_seller_profiles_status
        check (verification_status in ('PENDING', 'APPROVED', 'REJECTED')),
    constraint ck_seller_profiles_delivery_radius
        check (delivery_radius_km is null or delivery_radius_km >= 0),
    constraint ck_seller_profiles_latitude
        check (latitude is null or latitude between -90 and 90),
    constraint ck_seller_profiles_longitude
        check (longitude is null or longitude between -180 and 180)
);

create index if not exists idx_users_status on users (status);
create index if not exists idx_seller_profiles_verification_status
    on seller_profiles (verification_status);
