package org.example.matcheat.domain.account.service;

public enum AccountErrorCode {
    INVALID_EMAIL,
    VALIDATION_FAILED,
    PASSWORD_CONFIRM_MISMATCH,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    FORBIDDEN,
    ACCOUNT_SUSPENDED,
    ACCOUNT_WITHDRAWN,
    USER_NOT_FOUND,
    CURRENT_PASSWORD_MISMATCH,
    SELLER_APPLICATION_ALREADY_EXISTS,
    SELLER_APPLICATION_NOT_FOUND,
    SELLER_APPLICATION_ALREADY_REVIEWED,
    CANNOT_SUSPEND_SELF,
    ACTIVE_TRANSACTION_EXISTS,
    REPORT_NOT_FOUND,
    REPORT_TARGET_NOT_FOUND,
    REPORT_ALREADY_EXISTS,
    REPORT_ALREADY_REVIEWED,
    REPORT_RATE_LIMITED,
    PENALTY_ALREADY_EXISTS,
    INVALID_REPORT_STATUS
}
